# Generated by Django 4.2 on 2024-02-11 11:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название бренда(Brand`s name)')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название жанра(genre name)')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание категории(жанра)(Category descrition)')),
                ('url', models.SlugField(unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название тега(Tag name)')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название игры(Name of game)')),
                ('short_description', models.TextField(max_length=300, verbose_name='Краткое описание(Short_description)')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Полное описание(Full description)')),
                ('poster', models.ImageField(upload_to='media/posters', verbose_name='Обложка(Wrapper)')),
                ('age_limit', models.BooleanField(default=False, verbose_name='Ограничение по совершеннолетию(Age limit(18yo))')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовать(To publicate)')),
                ('aviable', models.BooleanField(default=True, verbose_name='Есть ли в наличии(Aviable)')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='КОличество на складе(Quantity on warehouse)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена товара(Product Price)')),
                ('url', models.SlugField(max_length=150, unique=True, verbose_name='Url')),
                ('year', models.PositiveSmallIntegerField(default=2014, verbose_name='Дата выхода(Premier Year)')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('categories', models.ManyToManyField(related_name='games', to='products.category', verbose_name='Категории(жанры)(Categories(genres))')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
